{ client_activate
	setvard PLAYER_IDX PARAM1
	setvard PLAYER_SERVER_ID $quote(PARAM2) 
	setvard MSG_TEXT PARAM3
	setvard IS_ACTIVE 1
	callevent 15.0 end_fx
	callevent test_loop
}

{ test_loop
	if IS_ACTIVE
	callevent 0.5 test_loop
	
	
	local STR_PLAYER_ORG $quote($getcl(PLAYER_IDX,origin)) 

	cleffect ce GM gm_clcmd_test MSG_TEXT STR_PLAYER_ORG PLAYER_SERVER_ID
}

{ end_fx
	setvard IS_ACTIVE 0
	callevent 0.2 remove_fx
}

{ remove_fx
	removescript
}
