#include monsters/debug

{ game_spawn
	setmodel test.mdl
	setsolid none
	setbbox none
	race beloved
	callevent 0.1 assign_num
}

{ assign_num
	if ( G_TESTG equals 'G_TESTG' )
	{
		setvarg G_TESTG 1
		setvard MY_NUM 1
	}
	else
	{
		setvard MY_NUM 2
	}
}

{ ext_go
	if ( MY_NUM == 1 ) playsound 0 10 1.wav
	if ( MY_NUM == 2 ) playsound 0 10 2.wav
}

{ set_scale
	consolemsg all set_scale PARAM1
	setprop ent_me scale PARAM1
}

{ set_org
	consolemsg all set_org PARAM1 PARAM2 PARAM3
	local L_MY_POS $get(ent_me,origin)
	vectoradd L_MY_POS $vec(PARAM1,PARAM2,PARAM3)
	setorigin ent_me L_MY_POS
}

{ face_me
	setmovedest PARAM1 9999
}

{ to_me
	consolemsg all to_me PARAM1
	setorigin $get(PARAM1,origin)
}

{ ext_playanim
	consolemsg all ext_playanim PARAM1
	setidleanim PARAM1
	setmoveanim PARAM1
	playanim critical PARAM1
}

{ ext_playsound
	consolemsg all ext_playsound PARAM1
	playsound 0 10 PARAM1
}

{ ext_cycle
	add C_STAGE 1
	if ( C_STAGE == 1 ) setvard CUR_ANIM @idle8
	if ( C_STAGE == 2 ) setvard CUR_ANIM !idle9
	if ( C_STAGE == 3 ) setvard CUR_ANIM !ready
	if ( C_STAGE == 4 ) setvard CUR_ANIM !mfuck1
	if ( C_STAGE == 5 ) setvard CUR_ANIM !mfuck1sp
	if ( C_STAGE == 6 ) setvard CUR_ANIM @WIN
	if ( C_STAGE == 7 ) setvard CUR_ANIM @play1
	if ( C_STAGE == 8 ) setvard CUR_ANIM @rape
	if ( C_STAGE == 9 ) setvard CUR_ANIM @fuck1
	if ( C_STAGE == 10 ) setvard CUR_ANIM @fuck1sp
	if ( C_STAGE == 11 ) setvard CUR_ANIM @fuck2
	if ( C_STAGE == 12 ) setvard CUR_ANIM @fuckend
	if ( C_STAGE == 12 ) setvard C_STAGE 0
	callevent ext_playanim CUR_ANIM
}

{ tog_solid
	if ( !AM_SOLID )
	{`m
		setvard AM_SOLID 1
		width 32
		height 64
		setsolid box
		setbbox npcsize
	}
	else
	{
		setvard AM_SOLID 0
		width 0
		height 0
		setsolid box
		setbbox npcsize
	}
}
