
{
	const BLACK_CHEST_LOC $relpos(0,64,0) 
	const BC_ITEM_LIST "armor_salamander;scroll2_summon_fangtooth;swords_rune_green;"
	const BC_ITEM_CHANCES "50;50;50;" 
	const BC_REQ_PLAYERS "1;1;1;"
	const BC_ITEM_NAMES "some Salamander Armor;a Summon Fangooth Scroll;a Green Rune Blade;"
	const BC_REQ_STAT maxhp
	const BC_REQ_STAT_LEVEL 300
	const BC_REQ_HP 200
	const BC_SPAWN_ON_USE 1

	setvar STORENAME testchest
}

{
   eventname treasure_spawn

   gold		100000
	name Developer Chest
}

#include items/base_treasurechest

{
   eventname chest_additems

	callevent add_gold 25 100 25
	
   
   
	
	
	
	
	
	
	

	addstoreitem STORENAME proj_arrow_jagged 60 0 0 60
	addstoreitem STORENAME mana_vampire 10 0   0
	addstoreitem STORENAME mana_regen 10 0   0
	addstoreitem STORENAME item_goblinhead 10 0   0
	addstoreitem STORENAME blunt_snake_staff 1 0
	addstoreitem STORENAME blunt_lightning 10 0
	addstoreitem STORENAME axes_golden 10 0
	addstoreitem STORENAME item_galat_note_10 1 0
	addstoreitem STORENAME item_galat_note_100 1 0
	addstoreitem STORENAME pack_boh 1 0
	addstoreitem STORENAME shields_urdual 1 0
	addstoreitem STORENAME smallarms_flamelick 1 0
	addstoreitem STORENAME swords_volcano 1 0
	addstoreitem STORENAME axes_greataxe 1 0
	addstoreitem STORENAME mana_forget 10 0
	addstoreitem STORENAME armor_helm_gaz1 1 0
	addstoreitem STORENAME armor_helm_gaz2 1 0
	addstoreitem STORENAME mana_demon_blood 10 0
	addstoreitem STORENAME item_crystal_reloc 10 0   0
	addstoreitem STORENAME swords_spiderblade 1 0 0
	addstoreitem STORENAME crest_noclicky 1 0
	addstoreitem STORENAME item_necro_note 1 0 0
	addstoreitem STORENAME smallarms_bone_blade 1 0   0
	addstoreitem STORENAME item_crow_shard 10 0
	addstoreitem STORENAME swords_giceblade 1   0
	addstoreitem STORENAME mana_resist_cold 2   0
	addstoreitem STORENAME item_torch 1   0
	addstoreitem STORENAME blunt_darkmaul 20   0
	addstoreitem STORENAME blunt_ravenmace 1   0
	addstoreitem STORENAME item_warbosshead 1   0
	addstoreitem STORENAME proj_arrow_gholy 300 0 0 60
	addstoreitem STORENAME swords_liceblade 1 0
	addstoreitem STORENAME mana_speed 1 0
	addstoreitem STORENAME mana_protection 1 0
	addstoreitem STORENAME mana_gprotection 1 0
	addstoreitem STORENAME blunt_gauntlets_fire 1 0
	addstoreitem STORENAME mana_immune_cold 1   0
	addstoreitem STORENAME proj_arrow_poison 60   0 0 30
	addstoreitem STORENAME smallarms_dagger 1   0
	addstoreitem STORENAME axes_scythe 1   0
	addstoreitem STORENAME blunt_calrianmace 1   0
	addstoreitem STORENAME blunt_granitemace 1   0
	addstoreitem STORENAME axes_doubleaxe 1   0
	addstoreitem STORENAME drink_ale 10 0   0
	addstoreitem STORENAME item_log 1 0   0
	addstoreitem STORENAME bows_swiftbow 1 0   0
	addstoreitem STORENAME swords_bastardsword 1 0   0
	addstoreitem STORENAME item_runicsymbol 3 0   0
	addstoreitem STORENAME item_runicsymbol2 3 0   0
	addstoreitem STORENAME swords_longsword 1 0   0
	addstoreitem STORENAME shields_buckler 1 0   0
	addstoreitem STORENAME shields_lironshield 1 0   0
	addstoreitem STORENAME shields_rune 1 0   0
	addstoreitem STORENAME swords_katana4 1 0   0
	addstoreitem STORENAME armor_golden 1 0   0
	addstoreitem STORENAME armor_dark 1 0   0
	addstoreitem STORENAME swords_iceblade 1   0
	addstoreitem STORENAME scroll_lightning_chain 5 0
	addstoreitem STORENAME scroll2_lightning_chain 5 0
	addstoreitem STORENAME scroll_blizzard 5 0
	addstoreitem STORENAME scroll_fire_ball 5 0
	addstoreitem STORENAME scroll_fire_dart 5 0
	addstoreitem STORENAME scroll_fire_wall 5 0
	addstoreitem STORENAME scroll_glow 5 0
	addstoreitem STORENAME scroll_ice_shield 5 0
	addstoreitem STORENAME scroll_ice_wall 5 0
	addstoreitem STORENAME scroll_lightning_storm 5 0
	addstoreitem STORENAME scroll_lightning_weak 5 0
	addstoreitem STORENAME scroll_poison 5 0
	addstoreitem STORENAME scroll_rejuvenate 5 0
	addstoreitem STORENAME scroll_summon_rat 5 0
	addstoreitem STORENAME scroll_summon_undead 5 0
	addstoreitem STORENAME scroll_volcano 5 0
	addstoreitem STORENAME scroll2_acid_bolt 5 0
	addstoreitem STORENAME scroll2_acid_xolt 5 0
	addstoreitem STORENAME scroll2_blizzard 5 0
	addstoreitem STORENAME scroll2_fire_ball 5 0
	addstoreitem STORENAME scroll2_fire_dart 5 0
	addstoreitem STORENAME scroll2_fire_wall 5 0
	addstoreitem STORENAME scroll2_frost_bolt 5 0
	addstoreitem STORENAME scroll2_frost_xolt 5 0
	addstoreitem STORENAME scroll2_glow 5 0
	addstoreitem STORENAME scroll2_ice_blast 5 0
	addstoreitem STORENAME scroll2_ice_shield 5 0
	addstoreitem STORENAME scroll2_ice_wall 5 0
	addstoreitem STORENAME scroll2_lightning_storm 5 0
	addstoreitem STORENAME scroll2_lightning_weak 5 0
	addstoreitem STORENAME scroll2_poison 5 0
	addstoreitem STORENAME scroll2_poison_cloud 5 0
	addstoreitem STORENAME scroll2_rejuvenate 5 0
	addstoreitem STORENAME scroll2_summon_rat 5 0
	addstoreitem STORENAME scroll2_summon_undead 5 0
	addstoreitem STORENAME scroll2_turn_undead 5 0
	addstoreitem STORENAME scroll2_volcano 5 0
}

{ trade_done


	callevent get_players 100


	callevent get_players 700


	callevent get_players 1000


	callevent get_players 20


	callevent get_players 5 1


	callevent get_players


	callevent get_players_by_stat skill.swordsmanship 10

}

{ game_container_addeditem
	messageall green game_container_addeditem PARAM2 PARAM2
}

{ game_container_gaveitem
	messageall green game_container_gaveitem PARAM2 PARAM2
}

{ game_attempt_unlock
	messageall green game_attempt_unlock PARAM2 PARAM2
}
