
{  [override] npcatk_attackenemy

    if ( ATTACK_DAMAGE == 'ATTACK_DAMAGE' ) setvar ATTACK_DAMAGE 5	
    if ( ATTACK_FREQUENCY == 'ATTACK_FREQUENCY' ) setvar ATTACK_FREQUENCY 10	

    
 	callevent can_reach_nme
    callevent npc_attack
    callevent npc_selectattack        

    setmovedest ent_lastseen MOVE_RANGE
    playanim once ANIM_ATTACK

    calleventtimed 1 do_stuff

    
    add ATTACK_COUNTER 1
    if ( ATTACK_COUNTER == ATTACK_FREQUENCY ) 
	{

		
		dodamage ent_lastseen ATTACK_HITRANGE ATTACK_DAMAGE ATTACK_HITCHANCE

		if ( ATTACK_HACK_STUN == 1 ) 
		{
			if ( $rand(1,ATTACK_HACK_STUNCHANCE) == 1 ) applyeffect ent_laststruckbyme effects/effect_stun 3 0
		}

	setvar ATTACK_COUNTER 0
    }


}

{ do_stuff

    
}
