
{
	setvar ANIM_IDLE	idle	
	setvar ANIM_WALK	walk	
	setvar ANIM_RUN	run	
	setvard ANIM_ATTACK	attack	

   const ATTACK_NORMAL_DAMAGE 	30
   const ATTACK_STANDING_DAMAGE $randf(18,33)
   const ATTACK_STOMPRANGE 	225
   const ATTACK_STOMPDMG 	30
   const ATTACK_HITCHANCE 	70%
   const NPC_BASE_EXP		190
}

#include monsters/bear_base_giant

{  npc_spawn

   hp 500
   
   name a|Giant Black bear

   setmodelbody	0 2
}
