
{
   const GORE_FORWARD_DAMAGE 	2
   const GORE_SIDE_DAMAGE 	1.2
   const BOAR_CAN_CHARGE	1
   const BOAR_CHARGE_DMG	4
   setvard HUNT_AGRO 		1	
   setvard CAN_HEAR		1	
   const FLEE_CHANCE		10%	

	const IS_HARD 1

   const NPC_BASE_EXP		9
}

#include monsters/boar

{  npc_spawn

   hp 25
   name a|Ferocious Wild Boar
   hearingsensitivity 2
	setmodel monsters/boar1.mdl

	if ( $lcase(game.map.name) equals nightmare_thornlands ) setmonsterclip 0
}
