{
	const EFFECT_SCRIPT effects/effect_poison
	const EFFECT_DURATION 10.0
}

#include monsters/scarab_fire

{ [override] [shared] scarab_spawn
	name a|Jade Scarab
	setmodel monsters/scarab.mdl
	hp 150
	width 16
	height 16
	roam 1
	race vermin
	hearingsensitivity 8
	
	takedmg holy 0.0
	blood green
	setmoveanim ANIM_MOVE
	setidleanim ANIM_IDLE
	setbbox npcsize 
	setsolid none
	setprop ent_me skin 1
}
