{
   	const NPC_BASE_EXP 200
	const MONSTER_MODEL monsters/gcobra_fire.mdl

	const DMG_EFFECT_SCRIPT effects/effect_burn
	const BREATH_EFFECT_SCRIPT effects/effect_burn

	const POISON_DAMAGE 30.0
	const POISON_DURATION 10.0 

	const PUSH_BREATH 1

	const CL_SCRIPT monsters/snake_gcobra_fire_cl

	const FIRE_BREATH 1 

	precache explode1.spr
}

#include monsters/snake_gcobra

{ npc_spawn
	name a|Fire Cobra
	takedmg fire 0.0
}
