{
	const SKILL_LEVEL_REQ 15
	const SKILL_TYPE skill.spellcasting

	const PET_TYPE wolf 
	const PET_SEARCH wolf_ice 
	const PET_MAXHP 1000 
	const PET_FAIL_MESSAGE "No weakened winter wolves in range."
	const PET_YAY_MESSAGE "You now have a new pet winter wolf!"
}

#include items/item_charm_w1

{ [override] crystal_spawn

	name a|Winter Wolf Charm
	desc This crystal can be used to tame one winter wolf
	weight 5
	size 5
	value 1000
	sethand both
}
