{
	const SKILL_LEVEL_REQ 0
	const SKILL_TYPE skill.spellcasting
	const SILENT_DELAY 1
}

#include items/base_crystal

{ crystal_spawn

	name a|Light Crystal
	desc These crystals of light become less corporeal with age
	weight 1 
	size 1
	value 10
	sethand both
	setvard ACTIVE_DELAY $randf(0,0.5)
}

{ activate_crystal

	
	
	callexternal all ext_flash_bang $get(ent_owner,origin) 128 $get(ent_owner,id)
	playermessage ent_owner You break the light crystal!
}
