
{
	const BASE_LEVEL_REQ 0
	const RANGE_SWIPE 64
	const POLEARM_OPTIMUM_RANGE 80 
	const POLEARM_DMG_FALLOFF 0.05 


	const SOUND_PARRY weapons/parry.wav

	
	const ANIM_LIFT         1
	const ANIM_IDLE1         0
	const ANIM_ATTACK1       2
	const ATTACK_ANIMS  1
	const ANIM_UNSHEATH       1
	const ANIM_SHEATH       1

	const ANIM_SWIPE 6
	const ANIM_SMASH 5
	const ANIM_POKE 4
	const ANIM_TRIP 3
	const ANIM_PARRY 7

	const MODEL_VIEW viewmodels/v_polearms.mdl 
	const MODEL_VIEW_IDX 4 

	const MODEL_HANDS weapons/p_weapons2.mdl 
	const MODEL_WORLD weapons/p_weapons2.mdl 

	const SOUND_SWIPE       weapons/swingsmall.wav
	const SOUND_HITWALL1       weapons/cbar_hit1.wav
	const SOUND_HITWALL2       weapons/cbar_hit2.wav
	const SOUND_DRAW       weapons/swords/sworddraw.wav 
	const SOUND_SHOUT $get(ent_owner,scriptvar,'PLR_SOUND_SHOUT1') 

	const MODEL_BODY_OFS 104 
	const ANIM_PREFIX  khopesh 

	
	
	const MELEE_RANGE  100
	const MELEE_DMG_DELAY  0.4
	const MELEE_ATK_DURATION 1.1
	const MELEE_DMG_DELAY_LONG 1.0
	const MELEE_ATK_DURATION_LONG 1.4
	const MELEE_ENERGY  1
	const MELEE_DMG  500 
	const MELEE_DMG_RANGE      0 
	const MELEE_DMG_TYPE  generic 
	const MELEE_ACCURACY  75%
	const MELEE_ACCURACY2  90%
	const MELEE_STAT  swordsmanship 
	const MELEE_ALIGN_BASE 3,10  
	const MELEE_ALIGN_TIP  0,-10 
	const MELEE_VIEWANIM_ATK      ANIM_ATTACK1

	const MELEE_SOUND      SOUND_SWIPE
	const MELEE_SOUND_DELAY      MELEE_DMG_DELAY
	const MELEE_PARRY_CHANCE      60%

	const PLAYERANIM_AIM  sword_double_idle 
	const PLAYERANIM_SWING sword_double_swing 
}

#include items/swords_base_twohanded

{ weapon_spawn

   name  a|Polearm (test)
   desc  It's a polearm! Really it is!
   weight  75
   size  9
   value 0 
   sethudsprite trade longsword 

   sethand both
}

{ [server] game_deploy

	setvard GAME_PVP game.pvp
}




{ [override] melee_start

	playowneranim once sword_double_swing 
	playviewanim  ANIM_ATTACK1
	volume 10
	playsound 1 SOUND_SWIPE

	if ( PARRY_MODE ) callevent end_parry
}

{ melee_damaged_other 
	local OUT_PAR1 PARAM1
	local OUT_PAR2 PARAM2
	callevent adjust_dmg OUT_PAR1 OUT_PAR2
}

{ special_01_damaged_other 
	local OUT_PAR1 PARAM1
	local OUT_PAR2 PARAM2
	callevent adjust_dmg OUT_PAR1 OUT_PAR2
}

{ adjust_dmg
	

	if $get(PARAM1,isalive)

	local OPTIMUM_RANGE POLEARM_OPTIMUM_RANGE
	local DMG_FALLOFF POLEARM_DMG_FALLOFF

	local TARG_RANGE $get(PARAM1,range)

	if TARG_RANGE != OPTIMUM_RANGE
	

	
	if ( TARG_RANGE > OPTIMUM_RANGE )
	{
		local MISSED_AMT TARG_RANGE
		subtract MISSED_AMT OPTIMUM_RANGE
		local TOO_CLOSE 0
	}
	if ( TARG_RANGE < OPTIMUM_RANGE )
	{
		local MISSED_AMT OPTIMUM_RANGE
		subtract MISSED_AMT TARG_RANGE
		local TOO_CLOSE 1
	}

	local DMG_PENALTY_FACTOR DMG_FALLOFF
	multiply DMG_PENALTY_FACTOR MISSED_AMT

	if ( DMG_PENALTY_FACTOR >= 1 )
	{
		local DMG_PENALTY_FACTOR 0.9 
		
	}

	local OUT_DMG_FACTOR 1
	subtract OUT_DMG_FACTOR DMG_PENALTY_FACTOR

	local OUT_DMG PARAM2
	multiply OUT_DMG OUT_DMG_FACTOR
	setdmg dmg OUT_DMG

	

}


{ [override] register_charge1

	

   
   

   local reg.attack.type		strike-land
   local reg.attack.keys		+attack1
   local reg.attack.range		MELEE_RANGE
   local reg.attack.dmg			MELEE_DMG
   local reg.attack.dmg.range		MELEE_DMG_RANGE
   local reg.attack.dmg.type		MELEE_DMG_TYPE
   local reg.attack.energydrain		MELEE_ENERGY
   local reg.attack.stat		MELEE_STAT
   local reg.attack.hitchance		MELEE_ACCURACY2
	
   local reg.attack.priority		0
   local reg.attack.delay.strike	MELEE_DMG_DELAY_LONG
   local reg.attack.delay.end		MELEE_ATK_DURATION_LONG
   local reg.attack.ofs.startpos	MELEE_STARTPOS
   local reg.attack.ofs.aimang		MELEE_AIMANGLE
   local reg.attack.callback		melee
   local reg.attack.noise		MELEE_NOISE

   local reg.attack.priority	1
   local reg.attack.keys	-attack1
   local reg.attack.callback	special_01
   multiply reg.attack.dmg	2
   local reg.attack.chargeamt	100%
   local reg.attack.reqskill	2
	add reg.attack.reqskill BASE_LEVEL_REQ

   registerattack



	

   
   

   local reg.attack.type		strike-land
   local reg.attack.keys		+attack1
   local reg.attack.range		MELEE_RANGE
   local reg.attack.dmg			0
   local reg.attack.dmg.range		0
   local reg.attack.dmg.type		generic
   local reg.attack.energydrain		MELEE_ENERGY
   local reg.attack.stat		MELEE_STAT
   local reg.attack.hitchance		MELEE_ACCURACY
   local reg.attack.priority		0
   local reg.attack.delay.strike	MELEE_DMG_DELAY_LONG
   local reg.attack.delay.end		MELEE_ATK_DURATION_LONG
   local reg.attack.ofs.startpos	MELEE_STARTPOS
   local reg.attack.ofs.aimang		MELEE_AIMANGLE
   local reg.attack.callback		melee
   local reg.attack.noise		MELEE_NOISE

   local reg.attack.priority	2
   local reg.attack.keys	-attack1
   local reg.attack.callback	special_02
   multiply reg.attack.dmg	2
   local reg.attack.chargeamt	200%
   local reg.attack.reqskill	5
	add reg.attack.reqskill BASE_LEVEL_REQ

   registerattack
}

{ [override] special_01_start
	if ( PARRY_MODE ) callevent end_parry
	playowneranim once sword_double_swing 
	playviewanim  ANIM_POKE
	volume 10
	playsound const.snd.weapon const.snd.maxvol SPECIAL01_SND
}

{ [override] special_02_start
	if ( PARRY_MODE ) callevent end_parry
	playowneranim once sword_double_swing 
	playviewanim  ANIM_SWIPE
	if game.serverside
	svplaysound 2 10 $get(ent_owner,scriptvar,'PLR_SOUND_SWORDREADY')
}

{ special_02_strike
	if game.serverside
	callexternal ent_owner ext_sphere_token enemy RANGE_SWIPE $get(ent_owner,origin)
	setvard SWIPE_LIST $get(ent_owner,scriptvar,'PLR_SCAN_TOKEN')

	if SWIPE_LIST isnot none
	local N_SWIPIES $get_token_amt(SWIPE_LIST)
	if N_SWIPIES > 0
	setvard OWNER_ORG $get(ent_owner,origin)
	setvard OWNER_ANG $get(ent_owner,angles)
	calleventloop N_SWIPIES swipe_targets
}

{ swipe_targets
	local CUR_TARGET $get_token(SWIPE_LIST,game.script.iteration)

	
	if ( $get(CUR_TARGET,isplayer) )
	{
		if !GAME_PVP
		local EXIT_SUB 1
	}
	if !EXIT_SUB

	
	if $get(CUR_TARGET,isalive)
	local TARG_ORG $get(CUR_TARGET,origin)
	if $within_cone2D(TARG_ORG,OWNER_ORG,OWNER_ANG,30)

	
	local TRACE_START OWNER_ORG
	local TRACE_END TARG_ORG
	if ( !$get(CUR_TARGET,isplayer) )
	{
		
		local HALF_MON_HEIGHT $get(CUR_TARGET,height)
		divide HALF_MON_HEIGHT 2
		vectoradd TRACE_END z HALF_MON_HEIGHT
	}
	local TRACE_CHECK $get_traceline(TRACE_START,TRACE_END,worldonly)
	if TRACE_CHECK equals TRACE_END

	
	local STAT_STR skill.
	stradd STAT_STR MELEE_STAT

	local STAT_SKILL $get(ent_owner,STAT_STR)
	local STAT_FLOAT STAT_SKILL
	multiply STAT_FLOAT 0.01

	local HIT_CHANCE 100
	subtract HIT_CHANCE MELEE_ACCURACY
	local HIT_CHANCE $get_skill_ratio(STAT_FLOAT,MELEE_ACCURACY,100) 

	local DMG_SWIPE MELEE_DMG
	local DMG_SWIPE $get_skill_ratio(STAT_FLOAT,0,MELEE_DMG)
	divide DMG_SWIPE 2 



	xdodamage CUR_TARGET direct DMG_SWIPE HIT_CHANCE ent_owner ent_owner STAT_STR MELEE_DMG_TYPE
}

{ game_+attack2

	if !PARRY_MODE
	if game.time > NEXT_PARRY
	setvard PARRY_MODE 1
	setvard game.effect.canattack 0	
	splayviewanim ent_me ANIM_PARRY
}

{ game_-attack2
	if PARRY_MODE
	callevent end_parry
}

{ game_takedamage 
	if PARRY_MODE
	if ( PARAM4 contains effect ) local EXIT_SUB 1
	if ( PARAM4 contains magic ) local EXIT_SUB 1
	if !EXIT_SUB
	local TARG_ORG $get(PARAM1,origin)
	setvard OWNER_ORG $get(ent_owner,origin)
	setvard OWNER_ANG $get(ent_owner,angles)
	if $within_cone2D(TARG_ORG,OWNER_ORG,OWNER_ANG,30)
	local DMG_TAKEN PARAM3
	local DMG_BLOCKED PARAM3
	multiply DMG_TAKEN 0.25
	multiply DMG_BLOCKED 0.75
	setdmg dmg DMG_TAKEN
	if ( DMG_BLOCKED > 0 ) local DMG_BLOCKED $int(DMG_BLOCKED)
	stradd DMG_BLOCKED pts
	playermessage Polearm blocked DMG_BLOCKED damage.
}

{ [override] item_idle

}

{ end_parry
	setvard NEXT_PARRY game.time
	add NEXT_PARRY 1.0
	setvard PARRY_MODE 0
	setvard game.effect.canattack 1
	splayviewanim ent_me ANIM_IDLE
}
