
{
	const CLFX_ARROW 1

   const ARROW_BODY_OFS      0
   const SPRITE_ARROW_TRADE   woodenarrow
   const PROJ_DAMAGE      $rand(30,60)
   const ARROW_STICK_DURATION   10   
   const ARROW_SOLIDIFY_ON_WALL   0     
   const ARROW_BREAK_CHANCE   20%   
     const ARROW_EXPIRE_DELAY    5
}

#include items/proj_arrow_base

{  arrow_spawn

   name       an|Arrow
   desc       A crudely made arrow
   weight       0.1
   size       1
   value      0.1
   gravity      0.75
   
   
   
}
