{
	const HITSCAN_BOLT 1
  	const MODEL_BODY_OFS		0

  	const PROJ_DAMAGE		400
	const PROJ_DAMAGE_TYPE holy
  	const PROJ_STICK_DURATION	25 	
  	const ARROW_SOLIDIFY_ON_WALL	1  	
  	const ARROW_BREAK_CHANCE	20%	
}

#include items/proj_arrow_base

{ arrow_spawn

	name 		a|Blessed Bolt
	desc 		A crossbow bolt blessed with enchanted silver to fight the unholy.
	weight 		0.4
	size 		1
	value		400
	gravity		0
	groupable	25
}
