
{
	const CLFX_ARROW 1
 
  const SPRITE_ARROW_TRADE	silverarrow	
  const PROJ_DAMAGE		$rand(275,375)
  const PROJ_STICK_DURATION	25	
  const ARROW_SOLIDIFY_ON_WALL	1  	
  const ARROW_BREAK_CHANCE	20%	
}

#include items/proj_arrow_base

{  arrow_spawn

	name 		Jagged Arrow
	desc 		When the target moves, the jags wound it
	weight 		0.2
	size 		3
	value		50
	gravity		0.8
	
	

	sethudsprite hand arrows
	sethudsprite trade SPRITE_ARROW_TRADE
	sethand any
}
