
{
	const CLFX_ARROW 1

	const SPRITE_ARROW_TRADE	firearrow	
	const ARROW_BODY_OFS		0
	const PROJ_DAMAGE_TYPE	holy
	const PROJ_DAMAGE		300
	const ARROW_STICK_DURATION	5 	
	const ARROW_SOLIDIFY_ON_WALL	0  	
	const ARROW_BREAK_CHANCE	50%	
  	const ARROW_EXPIRE_DELAY 	5
}

#include items/proj_arrow_base

{  arrow_spawn

	name 		Holy Arrow
	desc 		An arrow emdued with divine energies
	weight 		0.2
	size 		1
	value		300
	gravity		0.8
	groupable	15
}



	

	
