{
   const HITSCAN_BOLT 1
     const MODEL_BODY_OFS      0

     const PROJ_DAMAGE      100
     const PROJ_STICK_DURATION   25    
     const ARROW_SOLIDIFY_ON_WALL   0     
     const ARROW_BREAK_CHANCE   1%   
}

#include items/proj_arrow_base

{ arrow_spawn

   name       a|Crossbow Bolt
   desc       A crudely made bolt
   weight       0.2
   size       1
   value      0
   gravity      0
   groupable   25

   
}
