{
	const ITEM_EVENT add_epic_item
	const HP_REQ 500
	const MAX_GOLD_AMT 200
}

#include chests/base_treasurechest_array

{ chest_additems

	callevent add_gold_by_hp MAX_GOLD_AMT
	callevent ITEM_EVENT 100 HP_REQ

	if ( G_DEVELOPER_MODE ) saytext ITEM_EVENT HP_REQ

	
	if ( $lcase(game.map.name) equals the_wall )
	{
		local RND_CHEAT 50
		subtract RND_CHEAT $rand(1,50)
		if RND_CHEAT < game.playersnb
		addstoreitem STORENAME mana_flesheater2 1 0
	}
}
