

{
	setvar ANIM_IDLE	idle	
	setvar ANIM_WALK	walk	
	setvar ANIM_RUN	run	
	setvard ANIM_ATTACK	attack	

   const ATTACK_NORMAL_DAMAGE 	40
   const ATTACK_STANDING_DAMAGE $randf(28,30)
   const ATTACK_STOMPRANGE 	250
   const ATTACK_STOMPDMG 	80
   const ATTACK_HITCHANCE 	70%
   setvard NPC_GIVE_EXP		110
}

#include monsters/bear_base_giant

{  npc_spawn

   hp 1000
   
   name a|Murmur

   setmodelbody	0 1
}
