//Current issues: %%
//- base model needs sit, sit_wounded, sit_talk, and sit_2_stand anims
//- using the same quest type on the same map at the same time may cause issues (may just have to live with it)

//This is actually a base script, but can be dynamically created
//
//Requires the following
//
//const QUEST_TYPE escort_to|fetch_items|fetch_drop|kill_type|kill_target|defend_me
//
//const MODEL_YAW 90	//this will override the yaw used by any info_target the script maybe dependant on
//						//if the info_target has the angles property, it is not required
//
//const QUEST_ON_COMPLETE <fade>|<walk_fade> //on quest complete, fade away in spot, or attempt to walk away, and fade as I do?
//
//const QUEST_REWARD_EVENT <reward_map_based>|<reward_apple>|<reward_epic_minor>| (others as added or on top script...)
//

//const QUEST_DATA1 <varies with QUEST_TYPE>
//const QUEST_DATA2 <varies with QUEST_TYPE>
//
//QUEST_DATA formats are as follows by QUEST_TYPE:
//
//If QUEST_TYPE is "escort_to"
//- escort to location quest
//- QUEST_DATA1 <origin>|<target_name>
//- Quest completes when escorted to within 128 units of target location. (requires QUEST_FOLLOWER 1)
//
//If QUEST_TYPE is "fetch_items"
//- fetch item or items placed randomly throughout the map
//- QUEST_DATA1 <targetname_prefix> or <series of (vecs)>
//- QUEST_DATA2 "<qitem_code>;[qitem_name]"
//- QUEST_DATA3 <0|1> - spawn one item at available random locations, rather than one item at each location
//- if target name is used, assumes a series of info_target's named, for instance: fetch_item1 fetch_item2 fetch_item3
//- other/qitem will be spawned at this location. Item name name will be changed from the default qitem code if second token is provided in QUEST_DATA2.
//- Quest completes when all items are collected and returned.
//
//If QUEST_TYPE is "fetch_drop"
//- fetch items from monsters quest
//- QUEST_DATA1 "<num_required>;<monster_name|all>"
//- QUEST_DATA2 "<qitem_code>;[qitem_name]"
//- <num_required> the number of qitems that must be retrieved
//- <monster_name> will cause any monster with this string in its name to drop qitem
//- If monster_name is "all", any monster that dies on the map will drop qitem (except player pets, summons, and those lacking AI)
//- other/qitem will be spawned at monster corpses until quest completes. Item name will be changed from the default qitem code if second token is provided in QUEST_DATA2.
//- Quest completes when the required number of items are collected and returned.
//- * Having more than one fetch_drop quest active at the same time will cause issues!
//
//If QUEST_TYPE is "kill_type"
//- kill a number of monsters, or monsters of type
//- QUEST_DATA1 "<num_required>;<monster_name|all>"
//- QUEST_DATA2 "I think we killed enough of em! chat line"
//- <num_required> the number of monsters that must be slain
//- <monster_name> will cause any monster with this string in its name to add to the kill count when slain
//- If monster_name is "all", any monster on the map will add to the kill count (except player pets, summons, and those lacking AI)
//- Dwarf will use QUEST_DATA2 chatline when the required number of monsters are killed
//- Quest completes when the required number of monsters are slain and player speaks to dwarf
//- * Having more than one kill_type quest active at the same time will cause issues!
//
//If QUEST_TYPE is "kill_target"
//- causes a mini-boss to spawn at specific location that must be slain
//- QUEST_DATA1 "<monster_script>;<custom_boss_name>"
//- QUEST_DATA2 "<targetname>|<monster_origin>"
//- <monster_script> must have any media it uses precached (should be a type already on the map)
//- <targetname> inteded to be used with info_target on the map
//- Mini-boss will have 5x quest taker's HP (base)
//- Mini-boss XP value will be 2x quest taker's maxHP (base)
//- Mini-boss DOT will do 3%-7% of player's maxHP/tic (depending on type)
//- Mini-boss damage/strike will be capped at 50% player's maxHP
//- Mini-boss will recieve the npc_boss upgrade
//- Quest completes when mini-boss is slain, and player returns to dwarf
//
//If QUEST_TYPE is "defend_me"
//- Defend the quest giver from waves of monsters
//- QUEST_DATA1 "<monster_script>;<monster_script>;<monster_script>..."
//- QUEST_DATA2 "<num_required>"
//- Multiple <monster_script> can be used to create a series of random monsters
//- Their media must be precached, so it's based to use those already on the map
//- Monsters will attempt to spawn from 128 to 256 units from target up to 5 at a time (and manifest when a slot is free)
//- Attackers will have 50% of the quest taker's maxHP
//- Attacker's XP value will be 50% of quest taker's maxHP (base)
//- Attacker's DOT will do 2%-5% of player's maxHP/tic (depending on type)
//- Attacker's damage/strike will be capped at 50% player's maxHP
//- Game will enter "siege mode", meaning monsters that spawn on the map will target the CRITICAL_NPC quest giver until quest ends
//- Quest giver will periodically tell all monsters to target him if not already engaged
//- Quest completes when waves are defeated, and player's return to dwarf

//optional:
//const QUEST_FOLLOWER 1|0	//do I follow my activator or stay here? (required for escort)
//const QUEST_COMBATANT 0|1	//do I engage in combat, cower/flee?
//const QUEST_EXPERT_COMBATANT 0|1 //if combatant, unlocks special stun attack
//const QUEST_ACTIVE_COMBATANT 0|1 //if combatant, fight before quest activation (may die before players meet him)
//const QUEST_GIVER_NAME <string> - change name from default "a|Dwarven Miner"
//const NEW_RACE <race> - set beloved if you don't want attacked, defaults to human
//const AM_INVINCIBLE <0|1> - invulerable (might not be targeted as a result)
//const NEW_WIDTH <change width>
//const NEW_WIDTH <change height>
//const MONSTER_MODEL <new model> (must be precached - must have matching animations or the anims must be redefined in top script)
//const COMBAT_STRIKE_EVENT <evetname> (for use with new model with different anims - this is the eventname tied to the attack frame)
//const USE_SKIN <#> - otherwise dwarf skin will be randomized
//const USE_LANTERN <0|1> - has lantern
//const LANTERN_COLOR <(R,G,B)> defaults to: (128,64,0)
//const SUBMODEL_GROUPS "<group>|<subgroup>" (can define multiple pairs by repeating)
//const SET_SIEGE_MODE 0|1 (dwarf will become a CRITICAL_NPC target for all mobs on map when quest activated - default for defend_me.)
//const SET_LEADER 0|1 - instead of following player, will try to roam ahead to where he is facing (requires QUEST_FOLLOW 1)
//const INIT_IDLE_MODE <sitting|wounded|standing> - defaults to <wounded> for non-combatants, and <sitting> for combatants based on QUEST_COMBATANT setting
//const SOUND_HAIL none //sound when initially hailed (startle)
//(sound files for intro/complete can be handled through the template's quest_intro and quest_complete events

//Combat Behavior: 
//- dwarf will have double the HP of the player who picked up the quest (1000hp and beloved until activated)
//- If QUEST_COMBATANT is set, will do 5% of the quest taker's HP per attack, has no special attacks, but they can be rigged up in top script
//- quest dwarf heals as CRITICAL_NPC and provides damage points accordingly

//createnpc format is:
//createnpc dq\quest_dwarf <pos> <QUEST_TYPE> <QUEST_DATA1> <QUEST_DATA2> <QUEST_DATA3> <"Intro text"> <"Complete Text"> <reward_event> <spec_event|none> <yaw>

//Be sure to set angles on your info_target's

//current qitem codes:
//ap - "a|Golden Apple"
//bs - "a|Bag of Salt"
//bp - "a|Bag of Pepper"
//bm - "a|Barrel of Mead"
//la - "Sylphiel's Ladel"
//tnt - "a stick of|Dwarven Explosives"
//gen1 - "a|Package of Something" //(these use the generic item package model)*
//gen2 - "a|Package of Something" //(name intended to be changed via second createdyn param or title property)
//gen3 - "a|Package of Something"
//gen3 - "a|Package of Something"

#scope server
{
	//=========================================== Default Quest for Template Example
	//These defaults provide example quest configuration
	const QUEST_TYPE escort_to
	const QUEST_DATA1 $vec(0,0,0) //center of map on walltest.bsp
	const QUEST_FOLLOWER 1 //follows players on activation
	const QUEST_COMBATANT 0 //avoids combat
	const QUEST_ON_COMPLETE fade //fades away upon completion
	const QUEST_REWARD_EVENT reward_map_based //drop apple on win
	const USE_LANTERN 1
	const INIT_IDLE_MODE sitting

	//=========================================== Other Quest Script stuff (Employees Only)
	setvar QUEST_MODE waiting
	const CHAT_CONV_ANIMS DWARF_CONVO_ANIMS


	//=========================================== Dwarf Init
	//base ally
	setvard ALLY_FOLLOW_ON 0
	const ANIM_ALLY_JUMP anim_roll_back
	const SOUND_ALLY_JUMP voices/dwarf/vs_nx0drogm_hit2.wav
	const ALLY_MOVE_AWAY_DIST 128 //we seem to have a habit of landing on player's heads

	//base stuck
	const NPC_MATERIAL_TYPE flesh
	const NPC_USE_PAIN 1
	const NPC_USE_IDLE 0
	const NPC_USE_FLINCH 1 
	const SOUND_PAIN1 voices/dwarf/vs_ndwarfm1_hit1.wav
	const SOUND_PAIN2 voices/dwarf/vs_ndwarfm1_bat1.wav
	const SOUND_PAIN3 voices/dwarf/vs_ndwarfm1_hit3.wav
	const SOUND_FLINCH1 voices/dwarf/vs_nx0drogm_heal.wav
	const SOUND_FLINCH2 voices/dwarf/vs_nx0drogm_help.wav
	const SOUND_FLINCH3 voices/dwarf/vs_nx0drogm_hit1.wav
	const ANIM_FLINCH anim_xbow_flinch

	//base anims
	setvar ANIM_IDLE idle
	setvar ANIM_WALK walk
	setvar ANIM_RUN run
	setvard ANIM_DEATH death
	setvard ANIM_ATTACK attack	//alternates between leap and slash

	//base ai
	const NPC_BASE_EXP 0
	setvard NPC_NO_PLAYER_DMG 1
	setvard ATTACK_RANGE 75
	setvard ATTACK_HITRANGE 100
	setvard ATTACK_MOVERANGE 48
	const SOUND_DEATH voices/dwarf/vs_nx0drogm_hit3.wav

	//top
	setvard ATTACK_DAMAGE 50 //adjusts based on quest taker HP (5%)
	setvard ATTACK2_DAMAGE 150  //adjusts based on quest taker HP (15%)
	setvard ATTACK2_CHANCE 30 //only if QUEST_EXPERT_COMBATANT
	const ATTACK_ACCURACY 80
	const ATTACK2_ACCURACY 90
	const SOUND_ALERT1 voices/dwarf/voices/dwarf/vs_nx0drogm_bat3.wav
	const SOUND_ALERT2 voices/dwarf/voices/dwarf/vs_nx0drogm_bat1.wav
	const SOUND_ALERT3 voices/dwarf/voices/dwarf/vs_ndwarfm1_bat3.wav
	const SOUND_ATTACK1 voices/dwarf/voices/dwarf/vs_nx0drogm_atk1.wav
	const SOUND_ATTACK2 voices/dwarf/voices/dwarf/vs_nx0drogm_atk2.wav
	const SOUND_ATTACK3voices/dwarf/voices/dwarf/vs_nx0drogm_atk3.wav

	//new quest anims
	const ANIM_SIT_IDLE anim_sit_idle_lantern
	const ANIM_SIT_IDLE_NOLANTERN anim_sit_idle_nolantern
	const ANIM_SIT_IDLE_WOUNDED anim_sit_wounded
	const ANIM_SIT_IDLE_CONVO1 anim_convo1	
	const ANIM_SIT_IDLE_CONVO2 anim_convo2
}

#include monsters/base_monster_new
#include monsters/base_battle_ally
#include monsters/base_chat_array
#include monsters/base_struck
#include NPCs/dwarf_lantern_base

{ game_spawn
	callevent dwarf_spawn
}

{ dwarf_spawn
	name a|Dwarven Miner
	setmodel dwarf/male1.mdl
	if ( SET_SKIN isnot 'SET_SKIN' )
	{
		setprop ent_me skin $rand(0,6)
	}
	else
	{
		setprop ent_me skin SET_SKIN
	}
	setmodelbody 1 8
	width 32
	height 48
	roam 1
	hp 1000
	if ( !QUEST_ACTIVE_COMBATANT )
	{
		race beloved
	}
	else
	{
		race human
	}
	hearingsensitivity 8

	if ( INIT_IDLE_MODE equals sitting )
	{
		if ( USE_LANTERN )
		{
			setidleanim ANIM_SIT_IDLE 
		}
		else
		{
			setidleanim ANIM_SIT_IDLE_NOLANTERN
		}
		setvard AM_SITTING 1
	}
	else if ( INIT_IDLE_MODE equals wounded )
	{
		setidleanim ANIM_IDLE_WOUNDED
		setvard AM_SITTING 1
	}
	else if ( INIT_IDLE_MODE equals standing )
	{
		setidleanim ANIM_IDLE
	}

	if ( AM_STTING ) setvard DWARF_CONVO_ANIMS "anim_sit_convo1;anim_sit_convo2"
	else setvard DWARF_COMVO_ANIMS "anim_convo1;anim_convo2"
	
}

{ attack_1	//called by modelanim attack @frame 6

	//copypasta lazyness from dzomb
	dodamage NPCATK_TARGET ATTACK_HITRANGE ATTACK_DAMAGE ATTACK_ACCURACY
	if QUEST_EXPERT_COMBATANT
	if ( $rand(1,100) < ATTACK2_CHANCE ) setvard ANIM_ATTACK attack2
}

{ attack_2 //called by modelanim attack2 @frame 9

	playrandomsound 0 10 SOUND_ATTACK1 SOUND_ATTACK2 SOUND_ATTACK3

	//copypasta lazyness from dzomb
	dodamage NPCATK_TARGET ATTACK_HITRANGE ATTACK2_DAMAGE ATTACK2_ACCURACY
	setvard ANIM_ATTACK attack
	if $get(ent_laststruckbyme,range) <= ATTACK_HITRANGE
	applyeffect $get(ent_laststruckbyme,id) effects/heavy_stun $rand(2,8)
	applyeffect $get(ent_laststruckbyme,id) effects/effect_push 2 $relvel(10,-200,10) 0
}

{ set_leader
	if ( PARAM1 isnot 0 )
	{
		//speed up to stay in front
		movespeed 2.5
		setanim.movespeed 2.5
	}
	else
	{
		movespeed 1.0
		setanim.movespeed 1.0
	}
}

{ game_damaged
	//roll away if struck
	if !NPC_IS_TURRET
	if game.time > NEXT_DZOMB_FLEE
	setvard NEXT_DZOMB_FLEE game.time
	add NEXT_DZOMB_FLEE $randf(5,10)
	setvard AS_ATTACKING game.time
	add AS_ATTACKING 5.0
	svplaysound 2 10 SOUND_PAIN1
	playanim critical ANIM_DODGE

	local L_ROLL_DIR -200
	if ( AM_FLEEING ) local L_ROLL_DIR 200
	addvelocity ent_me $relvel(50,L_ROLL_DIR,100) 
}

{ frame_roll_back_push //ANIM_DODGE
	local L_ROLL_DIR -100
	if ( AM_FLEEING ) local L_ROLL_DIR 100
	addvelocity ent_me $relvel($randf(-50,50),L_ROLL_DIR,100) 
}

{ reward_map_based
	local L_MAPNAME $lcase(game.map.name)
	if ( L_MAPNAME equals walltest )
	{
		local L_REWARD_SACK chests/bag_o_gold_base
		local L_REWARD_PARAMS 66
	}
	else if ( L_MAPNAME equals edana )
	{
		local L_REWARD_SACK chests/bag_o_gold_base
		local L_REWARD_PARAMS 1
	}

	callevent do_reward L_REWARD_SACK L_REWARD_PARAMS
}

{ do_reward //<script> [params]
	local L_REWARD_SACK PARAM1
	local L_REWARD_PARAMS PARAM2
	createnpc L_REWARD_SACK $relpos(0,0,0) L_REWARD_PARAMS
}

{ game_menu_getoptions
	local L_CUR_USER PARAM1
	if ( $get(QUEST_TAKER,isalive) )
	{
		if L_CUR_USER isnot QUEST_TAKER
		dplayermessage PARAM1 NPC has engaged with $get(QUEST_TAKER,name)
		exitevent 
	}
	setvard QUEST_TAKER L_CUR_USER

	if !BUSY_CHATTING //need to obey busy flag here or he'll loop if exploited
	
	if ( QUEST_MODE equals waiting )
	{
		local reg.mitem.title 	"Hail"
		local reg.mitem.type 	callback
		local reg.mitem.callback quest_give_intro
		menuitem.register
	}
	else if ( QUEST_MODE equals asking )
	{
		local reg.mitem.title 	"Accept"
		local reg.mitem.type 	callback
		local reg.mitem.callback quest_activate
		menuitem.register
	}
	else if ( QUEST_MODE equals active )
	{
		local reg.mitem.title 	"(quest active)"
		local reg.mitem.type 	disabled
		menuitem.register
	}
	else if ( QUEST_MODE equals complete )
	{
		local reg.mitem.title 	"Turn in quest"
		local reg.mitem.type 	callback
		local reg.mitem.callback quest_complete
		menuitem.register
	}
}

{ game_menu_cancel
	if ( QUEST_MODE equals reqaccept ) setvard QUEST_GIVER unset
}

{ quest_give_intro
	playanim break
	playsound 0 10 SOUND_HAIL
	callevent quest_intro
	setvard SEND_LOOP 1
	setvard QUEST_MODE reqaccept
	callevent 5.0 send_quest_accept_req
}

{ send_quest_accept_req
	setvard QUEST_MODE asking
	menu.open QUEST_GIVER
}

{ quest_activate
	if ( QUEST_TYPE equals escort_to )
	{
		if ( QUEST_DATA1 startswith '(' )
		{
			setvard QUEST_DEST QUEST_DATA 1
		}
		else
		{
			local L_INFO $get_by_name(QUEST_DATA1)
			if ( !$get(L_INFO,exists) )
			{
				infomsg all "DWARF QUEST ERROR" "Cannot find info_target" QUEST_DATA1
			}
		}
		callevent quest_escort_to_monitor //loop this every second until within 128 units of QUEST_DEST
	}
}

{ quest_get_locations

}
