

{
	

}


{
	eventname game_spawn
	CheatEngineCheck
	
}

{ game_think
	if game.time > NEXT_BREATH
	setvard NEXT_BREATH game.time
	add NEXT_BREATH 0.1
	callevent player_breathe
}


{
	eventname game_jump

	
}
{
	eventname game_jump_land

	
}

{ game_hitground

	callevent player_hitgroundhard PARAM1
}

{
	eventname game_death

	
}

{ set_cl_gender_race
	setvard PLR_GENDER PARAM1
	setvard PLR_RACE PARAM2


}
