{ [shared]

	const MAP_NAME 		'goblin_town'
	const MAP_WEATHER 	clear;clear;clear;clear;clear;clear
	const MAP_ALLOWNIGHT 	0
	setvarg global.map.allownight 0
	setvarg MAP_CON 1
}

#include worlditems/map_startup

{ [client] game_newlevel	

 	if( PARAM1 equals 'goblintown' )
	{
		local reg.texture.name		'glass_bright'
		local reg.texture.reflect	1
		local reg.texture.reflect.blend	1
		local reg.texture.reflect.color	1;1;1;0.8
		local reg.texture.water		0
		
	}
}

