{
	const MAP_NAME 		'edanasewers'
	const MAP_WEATHER 	clear;clear;clear;clear;clear;clear
	const MAP_ALLOWNIGHT 	0

	setvarg MAP_CON 1
}

#include worlditems/map_startup

{ [client] game_newlevel	

	if PARAM1 equals MAP_NAME

	

	local reg.texture.name		'reflective'
	local reg.texture.reflect	1
	local reg.texture.reflect.blend	1
	local reg.texture.reflect.color	1;1;1;0.2
	local reg.texture.reflect.range	256
	local reg.texture.reflect.world	0
	local reg.texture.water		0
	registertexture
}
