
{
	setcallback touch enable
}

{ game_touch

	if !DID_TRIGGER
	if PARAM1 equals UNDAMAEL_ID

	

	if !$get(PARAM1,isplayer)
	

	usetrigger PARAM3
	setvard DID_TRIGGER 1
	callevent 0.1 remove_me
}

{ remove_me
	removescript
	deleteme
	
}

{ undamael_spawn
	setvard UNDAMAEL_ID $get_by_name(undamael)
}

{ [server] bd_debug  

	if ( RAND_ID equals 'RAND_ID' )
	{
		name pitbreak1
		setvard RAND_ID $rand(1000,9999)
	}
}

#include [server] monsters/debug
