
{
   eventname treasure_spawn

   
   setvar STORENAME	treasure_storeA34
}

#include items/base_treasurechest

{ chest_additems


	callevent add_gold 5 50 10

	
	addstoreitem  STORENAME     item_book_old	 1         0

	callevent get_chance 50 25 100 30
	if ( GIVE_PRIZE ) addstoreitem  STORENAME     blunt_club 	 1         0

	callevent get_chance 5 10 100 30
   if ( GIVE_PRIZE )
   {
   addstoreitem  STORENAME     swords_bastardsword	 	1   	    0
   }
}
