
{
   eventname treasure_spawn

   
   setvar	STORENAME nightmare_storeA32
}

#include items/base_treasurechest

{
   eventname chest_additems
	
	callevent add_gold 20 200 25
	callevent get_quantity 60 600 60 300

   
   addstoreitem STORENAME pack_archersquiver 1 0
   addstoreitem STORENAME proj_arrow_poison GIVE_QUANTITY 0 0 60
	if ( TC_NPLAYERS > 6 )
	{
		add_great_item 50
		callevent get_quantity 30 300 30 300
		addstoreitem STORENAME proj_arrow_gpoison GIVE_QUANTITY 0 0 60
	}
}
