
{
   const GORE_FORWARD_DAMAGE 	3
   const GORE_SIDE_DAMAGE 	1.5
   const ATTACK_HITPERCENT 	60%
   const BOAR_CAN_CHARGE	1
   const BOAR_CHARGE_DMG	9
   const NPC_BASE_EXP		15

}

#include monsters/boar_hard

{  npc_spawn

   hp 60
   takedmg all .81
   name a|Huge Aggressive Wild Boar
	setmodel monsters/boar1.mdl
   hearingsensitivity 4

   
   setvard CAN_FLEE 		0	
}

{ npc_post_spawn
	
	setvard DROP_ITEM1 skin_boar_heavy 	
	setvard DROP_ITEM1_CHANCE 100%		
}
