{ game_spawn

	invincible 1
	race beloved
	
	callevent 0.1 slithar_run_loop
}

{ slithar_run_loop
	
	if !MADE_IT

	callevent 0.5 slithar_run_loop

	

	local SLITHAR_NAME $get_by_name(snake_lord)
	local SLITHAR_ID $get(SLITHAR_NAME,id)
	local SLITHAR_RANGE $get(SLITHAR_ID,range)
	local MY_POS game.monster.origin 
	local MY_ID $get(ent_me,id)

	if !MADE_IT

	callexternal SLITHAR_ID slithar_to_me MY_POS SLITHAR_RANGE MY_ID
}

{ slithar_made_it
	setvard MADE_IT 1
	setalive 0
	deleteent ent_me	
}
