
{ game_learnskill 

	

	if PARAM2 equals 'Proficiency'
	if PARAM3 >= 2

	local TEXT "You have gained skill in proficiency. "
	stradd TEXT "|This trait unlocks new abilities with certain weapons."
	stradd TEXT "|To use them, double click attack to start charging."
	stradd TEXT "||Level 1 charge is usually extra damage.  With higher"
	stradd TEXT "|proficiency comes more advanced attacks."

	helptip ent_me help_skill_gain "Proficiency"  TEXT
}
